/*

 BG_WOWDOG_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 239

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __bg_wowdog_tiles_h_INCLUDE
#define __bg_wowdog_tiles_h_INCLUDE

/* Bank of tiles. */
#define bg_wowdog_tilesBank 0

/* Super Gameboy palette 0 */
#define bg_wowdog_tilesSGBPal0c0 0
#define bg_wowdog_tilesSGBPal0c1 23840
#define bg_wowdog_tilesSGBPal0c2 15164
#define bg_wowdog_tilesSGBPal0c3 15

/* Super Gameboy palette 1 */
#define bg_wowdog_tilesSGBPal1c0 6076
#define bg_wowdog_tilesSGBPal1c1 8935
#define bg_wowdog_tilesSGBPal1c2 6596
#define bg_wowdog_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define bg_wowdog_tilesSGBPal2c0 6076
#define bg_wowdog_tilesSGBPal2c1 8935
#define bg_wowdog_tilesSGBPal2c2 6596
#define bg_wowdog_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define bg_wowdog_tilesSGBPal3c0 6076
#define bg_wowdog_tilesSGBPal3c1 8935
#define bg_wowdog_tilesSGBPal3c2 6596
#define bg_wowdog_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define bg_wowdog_tilesCGBPal0c0 32767
#define bg_wowdog_tilesCGBPal0c1 20383
#define bg_wowdog_tilesCGBPal0c2 15166
#define bg_wowdog_tilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define bg_wowdog_tilesCGBPal1c0 32767
#define bg_wowdog_tilesCGBPal1c1 32725
#define bg_wowdog_tilesCGBPal1c2 32623
#define bg_wowdog_tilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define bg_wowdog_tilesCGBPal2c0 32767
#define bg_wowdog_tilesCGBPal2c1 21497
#define bg_wowdog_tilesCGBPal2c2 16367
#define bg_wowdog_tilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define bg_wowdog_tilesCGBPal3c0 29342
#define bg_wowdog_tilesCGBPal3c1 25884
#define bg_wowdog_tilesCGBPal3c2 18514
#define bg_wowdog_tilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define bg_wowdog_tilesCGBPal4c0 30614
#define bg_wowdog_tilesCGBPal4c1 30578
#define bg_wowdog_tilesCGBPal4c2 29520
#define bg_wowdog_tilesCGBPal4c3 25224

/* Gameboy Color palette 5 */
#define bg_wowdog_tilesCGBPal5c0 16233
#define bg_wowdog_tilesCGBPal5c1 15112
#define bg_wowdog_tilesCGBPal5c2 12935
#define bg_wowdog_tilesCGBPal5c3 11814

/* Gameboy Color palette 6 */
#define bg_wowdog_tilesCGBPal6c0 11892
#define bg_wowdog_tilesCGBPal6c1 10769
#define bg_wowdog_tilesCGBPal6c2 11814
#define bg_wowdog_tilesCGBPal6c3 8622

/* Gameboy Color palette 7 */
#define bg_wowdog_tilesCGBPal7c0 31697
#define bg_wowdog_tilesCGBPal7c1 26386
#define bg_wowdog_tilesCGBPal7c2 19970
#define bg_wowdog_tilesCGBPal7c3 0
/* Start of tile array. */
extern const unsigned char bg_wowdog_tiles[];

#endif

/* End of BG_WOWDOG_TILES.H */
