/*

 BG_WOWDOG_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : bg_wowdog.gbm.tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bg_wowdog_map_h_INCLUDE
#define __bg_wowdog_map_h_INCLUDE

#define bg_wowdog_mapWidth 20
#define bg_wowdog_mapHeight 18
#define bg_wowdog_mapBank 0

#define bg_wowdog_map bg_wowdog_mapPLN0
extern const unsigned char bg_wowdog_mapPLN0[];
extern const unsigned char bg_wowdog_mapPLN1[];

#endif

/* End of BG_WOWDOG_MAP.H */
